### ISSUE TITLE
Adaptation to new version of react-native-netinfo 5.0.0

### ISSUE THREAD

**Issue by Andersonfrfilho** [RobPando/redux-offline-queue#41]
### Adaptation to new version of react-native-netinfo 5.0.0
Thank you very much in advance.
after receiving the new reac-native-netinfo 5.0.0 update, what would be the way to get the case back
```js
import {put, take, call} from 'redux-saga / effects'
import {NetInfo} from 'react-native'
import {OFFLINE, ONLINE} from 'redux-offline-queue'

function * startWatchingNetworkConnectivity () {
  const channel = eventChannel ((emitter) => {
    NetInfo.isConnected.addEventListener ('connectionChange', emitter)
    return () => NetInfo.isConnected.removeEventListener ('connectionChange', emitter)
  })
  try {
    for (;;) {
      const isConnected = yield take (channel)
      if (isConnected) {
        yield put ({type: ONLINE})
      } else {
        yield put ({type: OFFLINE})
      }
    }
  } finally {
    channel.close ()
  }
}
```

**Comment by uellpalma** [comment]
I have a same problem with netinfo 5.2.0, you resolved ?

**Comment by Andersonfrfilho** [comment]
@uellpalma, 
I thank you for your interest.
Not yet the problem is that with the netinfo 5 update, it changed the way it handles the answers of its methods, so until the module creators adapt the modules for these new answers we have to use version 4 of Net-Info or opt for other modules. how:
`https://github.com/redux-offline/redux-offline`

**Comment by uellpalma** [comment]
Thank's for you answer.

**Comment by RobPando** [comment]
@Andersonfrfilho really really sorry for the late response. On to your concern, my question is: what exactly needs changing in in this package besides the readme? this package does not depend on netinfo, that is just a means to getting the connection state of your application. Can you give me more information please.

**Comment by gusbdev** [comment]
Hi guys. Sorry for the bad English. This adaptation of the new version of react-native-netinfo works for me.

```
const channel = eventChannel((emitter) => {
    const unsubscribe = NetInfo.addEventListener((state) => {
      let connectionState = state.isConnected;
      emitter(connectionState);
    });

    return () => unsubscribe();
});
```
