### ISSUE TITLE
Redux persist does not work

### ISSUE THREAD

**Issue by wallacerodrigon** [RobPando/redux-offline-queue#43]
When this lib is configured with redux-persist  as the documentation, It does not work well. I tried to put offline reducer into redux whitelist and Works, however the variable isConnected gets Crazy. The device is offline and the value of isConnected is equal true, because It is saved on redux storage. I tried to configure transform and solve part of this problem, but does not save the redux on persist when the device killed. I am Crazy with this offline libs and do not know what to do more. Any suggestion about that?

**Comment by RobPando** [comment]
@wallacerodrigon sorry for the late response. Did you find anything? There was a mistake in step 1 of the README (the naming of the store 'offline' is important) perhaps thats what it was messing your setup? if that was not it can you show me how you are configuring this library.
