### ISSUE TITLE
Is it possible to manually call consumeActionMiddleware ()?

### ISSUE THREAD

**Issue by Samuubs** [RobPando/redux-offline-queue#53]
Is it possible to manually call consumeActionMiddleware ()? I need the queue to be consumed as soon as the user logs in.

**Comment by RobPando** [comment]
@Samuubs This is not possible currently. What is the downside of adding it from the initial setup? if you have offline actions that are specific to a logged in user then this shouldn't post a problem, it will never queue those actions anyways unless the user is logged in, or am I missing something?
