### ISSUE TITLE
Types definition 

### ISSUE THREAD

**Issue by giorgiofellipe** [RobPando/redux-offline-queue#54]
Would be great if this lib had types definition, for using with Typescript.

**Comment by RobPando** [comment]
@giorgiofellipe will do!

**Comment by gleydson** [comment]
How is the development of this feature @RobPando? Can I help with anything?

I'm using this lib in a typescript project and I missed the types :(

**Comment by RobPando** [comment]
@gleydson I haven't had time to add these but I have set aside time this upcoming end of the week.

**Comment by RobPando** [comment]
@gleydson @giorgiofellipe Added the types declaration. I am planning on converting this project to typescript soon and when that happens I will be thorough and explicit with the type declaration but for now what I added should turn off the typescript error. Closing with 394307f2cfbf21ac22ab194c4b05f7ac8dd05045
